Only use results from GetWindowProperty if it returned Success
Since Xlib prior to 1.6 didn't always clear values on failure, don't
assume they're safe to use unless we succeeded.

Reported by Oracle Parfait 1.5.1:
Error: Uninitialised memory
   Uninitialised memory variable (CWE 457): Possible access to uninitialised memory variable 'ret_format'
        at line 743 of app/xcmsdb/xcmsdb.c in function 'RemoveSCCData'.
          ret_format allocated at line 733.
        at line 757 of app/xcmsdb/xcmsdb.c in function 'RemoveSCCData'.
          ret_format allocated at line 733.
   Uninitialised memory variable (CWE 457): Possible access to uninitialised memory variable 'ret_prop'
        at line 748 of app/xcmsdb/xcmsdb.c in function 'RemoveSCCData'.
          ret_prop allocated at line 731.
        at line 762 of app/xcmsdb/xcmsdb.c in function 'RemoveSCCData'.
          ret_prop allocated at line 731.

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Reviewed-by: Hans de Goede <hdegoede@redhat.com>